# Generated by Django 5.1 on 2024-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(),
        ),
    ]
