# Generated by Django 3.1.2 on 2025-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteflight',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoriteflight',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
